---
name: idr0070-kerwin-hdbr/experimentA
version: 1

defaults:
  # Should the column be processed when creating bulk-annotations (yes/no)
  include: false
  # Columns type of the bulk-annotations column
  type: string

  # If non-empty a string used to separate multiple fields in a column
  # White space will be stripped
  split:
  # Should this column be included in the clients (yes/no)
  includeclient: true
  # Should this column be visible in the clients, if no the column should be
  # hidden in the client but will still be indexed by the searcher (yes/no)
  visible: true
  # Should empty values be omitted from the client display
  omitempty: true

columns:

  - name: Assay Name
    include: true

  - name: Source Name
    include: true

  - name: Characteristics [Developmental Stage]
    clientname: Developmental Stage
    include: true

  - name: Protocol REF
    include: true

  - name: Comment [Probe]
    clientname: Probe
    include: true

  - name: Comment [Image File Comments]
    clientname: Image File Comments
    include: true

  - name: Channels
    include: true

  - name: Processed Data File
    include: true

  - name: Visualisation Method
    include: true

  - name: Expression Pattern Description
    include: true

  ######################################################################
  # mapr groups
  ######################################################################

  - group:
      namespace: openmicroscopy.org/mapr/organism
      columns:
        - name: Characteristics [Organism]
          clientname: Organism
          include: true

  - group:
      namespace: openmicroscopy.org/mapr/antibody
      columns:
        - name: Experimental Condition [Antibody]
          clientname: Antibody
          include: true
          omitempty: false
        - name: Antibody Identifier
          include: true
          omitempty: false
        - name: Antibody Identifier
          clientname: Antibody Identifier URL
          clientvalue: https://www.ncbi.nlm.nih.gov/nuccore/{{ value|urlencode }}
          include: true

  - group:
      namespace: openmicroscopy.org/mapr/gene
      columns:
        - name: Comment [Gene Identifier]
          clientname: Gene Identifier
          include: true
          omitempty: false
        - name: Comment [Gene Identifier]
          clientname: Gene Identifier URL
          clientvalue: http://www.ensembl.org/id/{{ value|urlencode }}
          include: true
        - name: Comment [Gene Symbol]
          clientname: Gene Symbol
          include: true
          omitempty: false


# Advanced options (experimental)
advanced:
  # If a map-annotation is attached to a well also attach it to all images
  # in the well
  well_to_images: true

  # TODO: Primary key config should be in a global config
  ignore_missing_primary_key: true
  primary_group_keys:
    - namespace: openmicroscopy.org/mapr/organism
      keys:
        - Organism
    - namespace: openmicroscopy.org/mapr/cell_line
      keys:
        - Cell Line
    - namespace: openmicroscopy.org/mapr/gene
      keys:
        - Gene Identifier
        - Gene Symbol
    - namespace: openmicroscopy.org/mapr/phenotype
      keys:
        - Phenotype